theme: jekyll-theme-hacker
title: "Pwn2Ninja Blog"

locale                   : "en-US"
title                    : "Pwn2Ninj4 Blog"
title_separator          : "-"
name                     : "Pwn2Ninj4"
description              : "Blog dedicado al exploiting, reversing y CTFs"
url                      : "https://pwn2ninj4.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "Pwn2Ninj4/pwn2ninj4.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
logo                     : "https://avatars.githubusercontent.com/u/76569311?s=400&u=4df44d6472fa779c006da24f6c9e1c3325093aee&v=4"
