theme: jekyll-theme-hacker
title: Pwn2Ninja Blog
menu:
    main:
      - name: Home
        url: ./
        weight: 1
      - name: Blog
        url: ./content/blog.md
        weight: 2
      - name: Exploiting
        url: ./exploiting.md
      - name: Reversing
        url: ./reversing.md
      - name: CTFs
        url: ./CTFs.md
      - name: Mas!
        url: ./random_posts.md
params:
  env: production
  ShowReadingTime: true
  
  profileMode:
    enabled: True
    Title: Hola 👋
    subtitle: "Mi nombre es Adrián Mederos aka Pwn2Ninja, son un aficionado a la programación en Python y me encanta la explotación y la ingeniería inversa"

  socialIcons:
    - name: twitter
      url: "https://twitter.com/D4n3xPwn?s=09"
    - name: github
      url: "https://github.com/Pwn2Ninja"
    - name: email
      url: "danex251@gmail.com"
